### ISSUE TITLE
App crashed if user cheated

### ISSUE THREAD

**Issue by shadwork** [Ognessa/Test#1]
Exception in thread "main" java.lang.IllegalArgumentException: bound must be greater than origin
	at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:337)
	at kotlin.random.jdk8.PlatformThreadLocalRandom.nextInt(PlatformThreadLocalRandom.kt:15)
	at kotlin.random.Random$Default.nextInt(Random.kt:284)
	at Number.generateNum(Main.kt:206)
	at Game.computerGuessNum(Main.kt:182)
	at Game.computerGuessNum(Main.kt:183)
	at Game.computerGuessNum(Main.kt:183)
	at Game.computerGuessNum(Main.kt:183)
	at Game.computerGuessNum(Main.kt:183)
	at Game.computerGuessNum(Main.kt:183)
	at Game.humanGuessNum(Main.kt:146)
	at Game.humanGuessNum(Main.kt:148)
	at Game.humanGuessNum(Main.kt:148)
	at Game.humanGuessNum(Main.kt:148)
	at Game.humanGuessNum(Main.kt:148)
	at MainKt.main(Main.kt:16)

**Comment by Ognessa** [comment]
Thank you, I'll fix it
